FROM node:20

WORKDIR /app

# Copy package files first for better caching
COPY package*.json ./
RUN npm install
RUN npm install --save-dev @types/bcryptjs

# Copy the rest of the application
COPY . .

EXPOSE 8000
CMD ["npm", "run", "dev"]